name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6


      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_COLOR: $({ job.status }) # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLCK_MESSAGE: 'Test Automation Report https://github.com/AbhishekYadav-SE/UI-CI-CD-/actions/runs/$({github.run_id})'
          SLACK_TITLE: Cypress Web Test
          SLACK_USERNAME: rtCamp
          Slack_WEBHOOK: 'https://hooks.slack.com/services/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'

